# Generated by Django 5.2.3 on 2025-07-07 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Hunarbaaz', 'Hunarbaaz'), ('Client', 'Client')], max_length=20)),
                ('query_type', models.CharField(choices=[('Feedback', 'Feedback'), ('Issue with Work Request', 'Issue with Work Request'), ('Profile/Login Issue', 'Profile/Login Issue'), ('Bug Report', 'Bug Report'), ('Website Suggestion', 'Website Suggestion'), ('Other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
