# Generated by Django 5.2.3 on 2025-07-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactreview',
            name='user',
        ),
        migrations.AddField(
            model_name='contactreview',
            name='email',
            field=models.EmailField(default='N/A', max_length=254),
        ),
        migrations.AddField(
            model_name='contactreview',
            name='name',
            field=models.CharField(default='User', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactreview',
            name='query_type',
            field=models.CharField(choices=[('General Inquiry', 'General Inquiry'), ('Want to Register as Hunarbaaz', 'Want to Register as Hunarbaaz'), ('Work Request Support', 'Work Request Support'), ('Appreciation or Feedback', 'Appreciation or Feedback'), ('Report an Issue', 'Report an Issue'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contactreview',
            name='user_type',
            field=models.CharField(choices=[('Hunarbaaz', 'Hunarbaaz'), ('Client', 'Client'), ('Visitor', 'Visitor')], max_length=20),
        ),
    ]
