# Generated by Django 5.2.3 on 2025-07-07 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_contactreview_user_contactreview_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactreview',
            name='rating',
        ),
    ]
