# Generated by Django 5.2.3 on 2025-07-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_contactreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactreview',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactreview',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
