# Generated by Django 5.2.3 on 2025-07-18 15:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hunarbaaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='mobile number must be exactly 10 digits', regex='^\\d{10}$')])),
                ('gender', models.CharField(choices=[('', '-------'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1, verbose_name='Gender')),
                ('skill', models.CharField(choices=[('', 'Tell us your skill'), ('Construction', 'Construction'), ('Electrician', 'Electrician'), ('Painter', 'Painter'), ('Domestic Worker', 'Domestic Worker'), ('Plumber', 'Plumber'), ('Carpenter', 'Carpenter'), ('Electronics Repair', 'Electronics Repair'), ('Mechanic', 'Mechanic'), ('Others', 'Others')], max_length=50)),
                ('location', models.CharField(choices=[('', 'Select you location'), ('Vallah/Verka', 'Vallah/Verka'), ('Hall Bazaar', 'Hall Bazaar'), ('Ranjit-Avenue', 'Ranjit-Avenue'), ('Company-bagh', 'Company-bagh'), ('Golden-gate', 'Golden-gate'), ('Putlighar', 'Putlighar'), ('Ramgharia gate', 'Ramgharia gate'), ('Batala-road', 'Batala-road'), ('Majitha-road', 'Majitha-road'), ('Ram Bagh', 'Ram Bagh'), ('other', 'other')], max_length=100)),
                ('experience', models.PositiveIntegerField(help_text='Years of experience')),
                ('aadhaar_number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Aadhaar number must be exactly 12 digits', regex='^\\d{12}$')])),
                ('wages', models.PositiveIntegerField(default=False, help_text='required pay for 8 hours')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='hunarbaaz/profile_pics/')),
                ('work_sample_1', models.ImageField(blank=True, null=True, upload_to='hunarbaaz/work_samples/')),
                ('work_sample_2', models.ImageField(blank=True, null=True, upload_to='hunarbaaz/work_samples/')),
                ('work_sample_3', models.ImageField(blank=True, null=True, upload_to='hunarbaaz/work_samples/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('job_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('rating', models.IntegerField(blank=True, help_text='Client rating after completion (1 to 5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_requests', to=settings.AUTH_USER_MODEL)),
                ('hunarbaaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_requests', to='hunarbaaz.hunarbaaz')),
            ],
        ),
    ]
