# Generated by Django 5.2.3 on 2025-07-12 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunarbaaz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hunarbaaz',
            name='password_plain',
        ),
        migrations.AlterField(
            model_name='hunarbaaz',
            name='mobile',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='mobile number must be exactly 10 digits', regex='^\\d{12}$')]),
        ),
    ]
