# Generated by Django 5.2.3 on 2025-07-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunarbaaz', '0002_workrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunarbaaz',
            name='password_plain',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='hunarbaaz',
            name='skill',
            field=models.CharField(choices=[('', 'Tell us your skill'), ('Construction', 'Construction'), ('Electrician', 'Electrician'), ('Painter', 'Painter'), ('Domestic Worker', 'Domestic Worker'), ('Plumber', 'Plumber'), ('Carpenter', 'Carpenter'), ('Electronics Repair', 'Electronics Repair'), ('Mechanic', 'Mechanic'), ('Welder', 'Welder'), ('Tailor', 'Tailor'), ('Cook', 'Cook'), ('Driver', 'Driver'), ('Others', 'Others')], max_length=50),
        ),
    ]
