# Generated by Django 5.2.3 on 2025-07-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunarbaaz', '0003_hunarbaaz_password_plain_alter_hunarbaaz_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunarbaaz',
            name='location',
            field=models.CharField(choices=[('', 'select you location'), ('Vallah/Verka', 'Vallah/Verka'), ('Hall Bazaar', 'Hall Bazaar'), ('Ranjit-Avenue', 'Ranjit-Avenue'), ('Company-bagh', 'Company-bagh'), ('Golden-gate', 'Golden-gate'), ('Putlighar', 'Putlighar'), ('Ramgharia gate', 'Ramgharia gate'), ('Batala-road', 'Batala-road'), ('Majitha-road', 'Majitha-road'), ('Ram Bagh', 'Ram Bagh'), ('other', 'other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='hunarbaaz',
            name='skill',
            field=models.CharField(choices=[('', 'Tell us your skill'), ('Construction', 'Construction'), ('Electrician', 'Electrician'), ('Painter', 'Painter'), ('Domestic Worker', 'Domestic Worker'), ('Plumber', 'Plumber'), ('Carpenter', 'Carpenter'), ('Electronics Repair', 'Electronics Repair'), ('Mechanic', 'Mechanic'), ('Others', 'Others')], max_length=50),
        ),
    ]
