# Generated by Django 5.2.3 on 2025-07-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunarbaaz', '0004_hunarbaaz_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunarbaaz',
            name='location',
            field=models.CharField(choices=[('', 'Select you location'), ('Vallah/Verka', 'Vallah/Verka'), ('Hall Bazaar', 'Hall Bazaar'), ('Ranjit-Avenue', 'Ranjit-Avenue'), ('Company-bagh', 'Company-bagh'), ('Golden-gate', 'Golden-gate'), ('Putlighar', 'Putlighar'), ('Ramgharia gate', 'Ramgharia gate'), ('Batala-road', 'Batala-road'), ('Majitha-road', 'Majitha-road'), ('Ram Bagh', 'Ram Bagh'), ('other', 'other')], max_length=100),
        ),
    ]
