# Generated by Django 5.2.3 on 2025-07-07 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunarbaaz', '0004_alter_hunarbaaz_location_alter_hunarbaaz_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunarbaaz',
            name='aadhaar_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Aadhaar number must be exactly 12 digits', regex='^\\d{12}$')]),
        ),
    ]
