# Generated by Django 5.2.3 on 2025-07-18 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunarbaaz', '0005_alter_hunarbaaz_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunarbaaz',
            name='mobile',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='mobile number must be exactly 10 digits', regex='^\\d{10}$')]),
        ),
    ]
