# Generated by Django 5.2.3 on 2025-07-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunarbaaz', '0005_alter_hunarbaaz_aadhaar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunarbaaz',
            name='wages',
            field=models.PositiveIntegerField(default=False, help_text='required pay for 8 hours'),
        ),
    ]
