# Generated by Django 5.2.3 on 2025-07-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunarbaaz', '0006_hunarbaaz_wages'),
        ('hunarbaaz', '0006_rename_client_name_workrequest_location_and_more'),
    ]

    operations = [
    ]
