# Generated by Django 5.2.3 on 2025-07-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunarbaaz', '0008_alter_workrequest_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hunarbaaz',
            old_name='work_sample',
            new_name='work_sample_1',
        ),
        migrations.AddField(
            model_name='hunarbaaz',
            name='work_sample_2',
            field=models.ImageField(blank=True, null=True, upload_to='hunarbaaz/work_samples/'),
        ),
        migrations.AddField(
            model_name='hunarbaaz',
            name='work_sample_3',
            field=models.ImageField(blank=True, null=True, upload_to='hunarbaaz/work_samples/'),
        ),
    ]
