# Generated by Django 5.2.3 on 2025-07-12 12:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hunarbaaz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='client fullname', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('work_type', models.CharField(choices=[('', '<<<--Select-->>>'), ('Residential', 'Residential'), ('Commercial', 'Commercial')], default='N/A', max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='client/profile_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, help_text='Start date of the job')),
                ('end_date', models.DateField(blank=True, help_text='Expected completion date')),
                ('job_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', help_text='Type of job location', max_length=20)),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False, help_text='Whether the client has cancelled the request')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(blank=True, help_text='Client rating after completion (1 to 5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, help_text='Optional client feedback', null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
                ('hunarbaaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='hunarbaaz.hunarbaaz')),
            ],
        ),
    ]
