# Generated by Django 5.2.3 on 2025-07-02 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('hunarbaaz', '0002_workrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('scheduled_date', models.DateField()),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
                ('hunarbaaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='hunarbaaz.hunarbaaz')),
            ],
        ),
    ]
