# Generated by Django 5.2.3 on 2025-07-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_postrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='fullname',
            field=models.CharField(default='null'),
        ),
    ]
