# Generated by Django 5.2.3 on 2025-07-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_postrequest_working_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='work_type',
        ),
    ]
