# Generated by Django 5.2.3 on 2025-07-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_clientprofile_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='fullname',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='full_name',
            field=models.CharField(default='client fullname', max_length=20),
        ),
    ]
