# Generated by Django 5.2.3 on 2025-07-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_clientprofile_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other / Prefer not to say')], default='M', max_length=1, verbose_name='Gender'),
        ),
    ]
