# Generated by Django 5.2.3 on 2025-07-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_clientprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='gender',
            field=models.CharField(choices=[('', '-------'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1, verbose_name='Gender'),
        ),
    ]
