# Generated by Django 5.2.3 on 2025-07-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_clientprofile_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrequest',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
