# Generated by Django 5.2.3 on 2025-07-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_postrequest_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='company_name',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='work_type',
            field=models.CharField(choices=[('', 'Work Category'), ('Residential', 'Residential'), ('Commercial', 'Commercial')], default='N/A', max_length=20),
        ),
    ]
