# Generated by Django 5.2.3 on 2025-07-16 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_clientprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='mobile number must be exactly 10 digits', regex='^\\d{10}$')]),
        ),
    ]
