# Generated by Django 5.2.3 on 2025-07-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_remove_clientprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='work_type',
            field=models.CharField(choices=[('', '<<<--Select-->>>'), ('Residential', 'Residential'), ('Commercial', 'Commercial')], default='N/A', max_length=20),
        ),
    ]
