# Generated by Django 5.2.3 on 2025-07-07 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_clientprofile_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrequest',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='postrequest',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
