# Generated by Django 5.2.3 on 2025-07-07 17:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_postrequest_rating_postrequest_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrequest',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))]),
        ),
    ]
