# Generated by Django 5.2.3 on 2025-07-08 15:56

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_postrequest_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postrequest',
            name='scheduled_date',
        ),
        migrations.AddField(
            model_name='postrequest',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Expected completion date'),
        ),
        migrations.AddField(
            model_name='postrequest',
            name='job_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', help_text='Type of job location', max_length=20),
        ),
        migrations.AddField(
            model_name='postrequest',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Start date of the job'),
        ),
        migrations.AlterField(
            model_name='postrequest',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Client rating after completion (1.0 - 5.0)', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))]),
        ),
        migrations.AlterField(
            model_name='postrequest',
            name='review',
            field=models.TextField(blank=True, help_text='Optional client feedback', null=True),
        ),
    ]
