# Generated by Django 5.2.3 on 2025-07-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_remove_postrequest_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrequest',
            name='end_date',
            field=models.DateField(blank=True, help_text='Expected completion date'),
        ),
        migrations.AlterField(
            model_name='postrequest',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date of the job'),
        ),
    ]
