# Generated by Django 5.2.3 on 2025-07-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_postrequest_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrequest',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Whether the client has cancelled the request'),
        ),
    ]
