# Generated by Django 5.2.3 on 2025-07-09 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_postrequest_is_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrequest',
            name='rating',
            field=models.IntegerField(blank=True, help_text='Client rating after completion (1 to 5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
