# Generated by Django 5.2.3 on 2025-07-01 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hunarbaaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('skill', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField(help_text='Years of experience')),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='hunarbaaz/profile_pics/')),
                ('work_sample', models.ImageField(blank=True, null=True, upload_to='hunarbaaz/work_samples/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
